/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as NuevoRouteImport } from './routes/nuevo'
import { Route as CultivoIdRouteImport } from './routes/cultivo.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevoRoute = NuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const CultivoIdRoute = CultivoIdRouteImport.update({
  id: '/cultivo/$id',
  path: '/cultivo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guia': typeof GuiaRoute
  '/nuevo': typeof NuevoRoute
  '/cultivo/$id': typeof CultivoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guia': typeof GuiaRoute
  '/nuevo': typeof NuevoRoute
  '/cultivo/$id': typeof CultivoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guia': typeof GuiaRoute
  '/nuevo': typeof NuevoRoute
  '/cultivo/$id': typeof CultivoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/guia' | '/nuevo' | '/cultivo/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guia' | '/nuevo' | '/cultivo/$id'
  id: '__root__' | '/' | '/guia' | '/nuevo' | '/cultivo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuiaRoute: typeof GuiaRoute
  NuevoRoute: typeof NuevoRoute
  CultivoIdRoute: typeof CultivoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuevo': {
      id: '/nuevo'
      path: '/nuevo'
      fullPath: '/nuevo'
      preLoaderRoute: typeof NuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cultivo/$id': {
      id: '/cultivo/$id'
      path: '/cultivo/$id'
      fullPath: '/cultivo/$id'
      preLoaderRoute: typeof CultivoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuiaRoute: GuiaRoute,
  NuevoRoute: NuevoRoute,
  CultivoIdRoute: CultivoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
